#!/usr/bin/python3
# SPDX-FilecopyrightText: 2022 Sho Konosu
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)


ans1 = 0
ans2 = 1
ans3 = 0
for line in sys.stdin:
    line = line.rstrip()
    ans1 += float(line)
    ans2 *= float(line)
    ans3 -= float(line)

print(ans1)
print(ans2)
print(ans3)
